# Generated by Django 5.2.9 on 2025-12-28 21:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_role_userbranchaccess_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregister',
            name='public_id',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.AddField(
            model_name='cashsession',
            name='public_id',
            field=models.UUIDField(null=True, editable=False,),
        ),
    ]
