# Generated by Django 5.2.9 on 2025-12-28 21:10

from django.db import migrations
import uuid


def populate_public_ids(apps, schema_editor):
    CashRegister = apps.get_model("core", "CashRegister")
    CashSession = apps.get_model("core", "CashSession")

    for register in CashRegister.objects.filter(public_id__isnull=True):
        register.public_id = uuid.uuid4()
        register.save(update_fields=["public_id"])

    for session in CashSession.objects.filter(public_id__isnull=True):
        session.public_id = uuid.uuid4()
        session.save(update_fields=["public_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_cashregister_public_id_cashsession_public_id"),  # AJUSTA AL NOMBRE REAL
    ]

    operations = [
        migrations.RunPython(populate_public_ids),
    ]

