# Generated by Django 5.2.9 on 2025-12-28 21:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_populate_cashregister_public_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashregister",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
        migrations.AlterField(
            model_name="cashsession",
            name="public_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True, editable=False),
        ),
    ]
