# Generated by Django 5.2.9 on 2025-12-29 00:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_enforce_public_id_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('movement_type', models.CharField(choices=[('TRANSFER_IN', 'Transferencia Entrante'), ('TRANSFER_OUT', 'Transferencia Saliente'), ('ADJUSTMENT_IN', 'Ajuste Sobrante'), ('ADJUSTMENT_OUT', 'Ajuste Faltante')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to='core.branch')),
                ('cash_register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.cashregister')),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.cashsession')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
            },
        ),
    ]
