# Generated by Django 5.2.9 on 2025-12-30 15:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cashmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contract_number', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activo'), ('CLOSED', 'Cerrado'), ('DEFAULTED', 'En mora')], default='ACTIVE', max_length=20)),
                ('customer_full_name', models.CharField(max_length=120)),
                ('customer_ci', models.CharField(blank=True, default='', max_length=30)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_rate_monthly', models.DecimalField(decimal_places=2, default=8.0, max_digits=6)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('interest_mode', models.CharField(default='MONTHLY_PRORATED', help_text='MONTHLY_PRORATED (por días) / FIXED / PROMO', max_length=20)),
                ('promo_note', models.CharField(blank=True, default='', max_length=255)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.branch')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_contracts', to=settings.AUTH_USER_MODEL)),
                ('disbursed_cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_disbursements', to='core.cashsession')),
            ],
        ),
    ]
