# Generated by Django 5.2.9 on 2025-12-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_pawncontract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('TRANSFER_IN', 'Transferencia Entrante'), ('TRANSFER_OUT', 'Transferencia Saliente'), ('ADJUSTMENT_IN', 'Ajuste Sobrante'), ('ADJUSTMENT_OUT', 'Ajuste Faltante'), ('LOAN_OUT', 'Desembolso Préstamo'), ('PAYMENT_IN', 'Pago/Abono')], max_length=20),
        ),
        migrations.CreateModel(
            name='BranchCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pawn_contract_seq', models.PositiveIntegerField(default=0)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='counter', to='core.branch')),
            ],
        ),
    ]
