# Generated by Django 5.2.9 on 2025-12-30 15:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cashmovement_movement_type_branchcounter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('principal_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_payments', to='core.cashsession')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='core.pawncontract')),
                ('paid_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_payments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
