# Generated by Django 5.2.9 on 2025-12-30 16:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pawnpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('renewed_at', models.DateTimeField(auto_now_add=True)),
                ('previous_due_date', models.DateField()),
                ('new_due_date', models.DateField()),
                ('amount_charged', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fee_charged', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('cash_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_renewals', to='core.cashsession')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renewals', to='core.pawncontract')),
                ('renewed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pawn_renewals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
