# Generated by Django 5.2.9 on 2025-12-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pawnrenewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawncontract',
            name='interest_accrued_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
