# Generated by Django 5.2.9 on 2026-01-27 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pawncontract_interest_accrued_until'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(choices=[('PORTATIL', 'Portátil'), ('PC', 'PC Escritorio'), ('CELULAR', 'Celular'), ('TV', 'Televisor'), ('REFRIGERADOR', 'Refrigerador'), ('COCINA', 'Cocina'), ('GARRAFA', 'Garrafa'), ('JOYA_ORO', 'Joya de oro'), ('RADIO', 'Radio/Equipo'), ('PLAYSTATION', 'PlayStation/Consola'), ('INSTRUMENTO', 'Instrumento musical'), ('OTRO', 'Otro')], max_length=30)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('has_box', models.BooleanField(default=False)),
                ('has_charger', models.BooleanField(default=False)),
                ('observations', models.TextField(blank=True, default='')),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='core.pawncontract')),
            ],
        ),
    ]
