# Generated by Django 5.2.9 on 2026-04-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pawnitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawnitem',
            name='category',
            field=models.CharField(choices=[('LAPTOP', 'Laptop'), ('PHONE', 'Celular'), ('JEWELRY', 'Joya'), ('APPLIANCE', 'Electrodoméstico'), ('CONSOLE', 'Consola'), ('INSTRUMENT', 'Instrumento musical'), ('OTHER', 'Otro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pawnitem',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.pawncontract'),
        ),
        migrations.AlterField(
            model_name='pawnitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='pawnitem',
            name='observations',
            field=models.TextField(blank=True),
        ),
    ]
