# Generated by Django 5.2.9 on 2026-04-05 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_transfer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('ci', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InvestorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='core.investor')),
            ],
        ),
        migrations.CreateModel(
            name='InvestorMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('movement_type', models.CharField(choices=[('DEPOSIT', 'Ingreso'), ('ASSIGN', 'Asignado a contrato'), ('RETURN', 'Retorno de capital'), ('PROFIT', 'Ganancia'), ('WITHDRAW', 'Retiro')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='core.investor')),
                ('related_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.pawncontract')),
            ],
        ),
    ]
