# Generated by Django 5.2.9 on 2026-04-05 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_investor_investoraccount_investormovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawncontract',
            name='investor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='core.investor'),
        ),
    ]
