# Generated by Django 5.2.9 on 2026-04-16 02:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_directpurchase_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnrenewal',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aguinaldoperiod',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe calculado: (sueldo/12) × meses_proporcionales.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='aguinaldoperiod',
            name='days_worked_in_year',
            field=models.PositiveSmallIntegerField(default=0, help_text='Días efectivamente trabajados en el año (mínimo 90 para calificar).'),
        ),
        migrations.AlterField(
            model_name='aguinaldoperiod',
            name='hire_date_snapshot',
            field=models.DateField(help_text='Fecha de ingreso al momento del cálculo (para auditoría).'),
        ),
        migrations.AlterField(
            model_name='aguinaldoperiod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aguinaldoperiod',
            name='months_in_period',
            field=models.DecimalField(decimal_places=2, help_text='Meses proporcionales trabajados en el año (max 11 para regular).', max_digits=4),
        ),
        migrations.AlterField(
            model_name='aguinaldoperiod',
            name='qualifies',
            field=models.BooleanField(default=True, help_text='False si el empleado no cumple los 90 días mínimos.'),
        ),
        migrations.AlterField(
            model_name='appraisaloverride',
            name='contract',
            field=models.OneToOneField(blank=True, help_text='Contrato creado tras la autorización (null mientras está pendiente)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appraisal_override', to='core.pawncontract'),
        ),
        migrations.AlterField(
            model_name='appraisaloverride',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='appraisaloverride',
            name='system_max_allowed',
            field=models.DecimalField(decimal_places=2, help_text='Máximo antes del bloqueo duro', max_digits=12),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='date',
            field=models.DateField(help_text='Fecha de la jornada.'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='night_hours',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Horas trabajadas después de las 20:00.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='cashdenomination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashexpense',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='movement_type',
            field=models.CharField(choices=[('CAPITAL_IN', 'Inyección de Capital'), ('CAPITAL_OUT', 'Retiro de Capital / Utilidad'), ('TRANSFER_IN', 'Transferencia Entrante'), ('TRANSFER_OUT', 'Transferencia Saliente'), ('ADJUSTMENT_IN', 'Ajuste Sobrante'), ('ADJUSTMENT_OUT', 'Ajuste Faltante'), ('LOAN_OUT', 'CN – Desembolso de Contrato'), ('PAYMENT_IN', 'CC/UC – Cobro de Contrato'), ('PURCHASE_OUT', 'CD – Compra Directa'), ('EXPENSE_OUT', 'G – Gasto Operativo'), ('VAULT_IN', 'Ingreso a Bóveda'), ('VAULT_OUT', 'Salida de Bóveda')], max_length=20),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='actual_profit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='UV = Precio venta - Costo CD', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='market_value_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimado del valor de mercado (base para calcular oferta MVI)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Monto pagado al vendedor (CD – salida de caja)', max_digits=12),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='pvp',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio de vitrina asignado por el dueño', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchase',
            name='qr_code_data',
            field=models.CharField(blank=True, help_text='UUID del artículo codificado en el QR', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='directpurchasephoto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, help_text='Sueldo básico actual en Bs.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(help_text='Sucursal donde trabaja el empleado.', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='core.branch'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cash_register',
            field=models.ForeignKey(blank=True, help_text='Caja asignada (para deslinde de responsabilidades en faltantes).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_employees', to='core.cashregister'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ci',
            field=models.CharField(help_text='Cédula de Identidad', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ci_scan',
            field=models.FileField(blank=True, help_text='Carnet de identidad escaneado.', null=True, upload_to='hr/ci_scans/%Y/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='complemento_ci',
            field=models.CharField(blank=True, default='', help_text='Complemento CI (1A, 2B…)', max_length=5),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_file',
            field=models.FileField(blank=True, help_text='Contrato firmado (PDF/imagen).', null=True, upload_to='hr/contracts/%Y/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='domicile_sketch',
            field=models.FileField(blank=True, help_text='Croquis de domicilio.', null=True, upload_to='hr/domiciles/%Y/'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(help_text='Fecha de ingreso oficial.'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nua_cua',
            field=models.CharField(blank=True, default='', help_text='NUA/CUA para aportes AFP/Gestora. Dejar en blanco si no aplica.', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='trial_end_date',
            field=models.DateField(blank=True, help_text='Fin del período de prueba (max 90 días según LGT).', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(help_text='Cuenta de usuario del sistema asignada a este empleado.', on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeetermination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hrconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='profit_rate_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Porcentaje de la utilidad (interés) que corresponde al inversionista. Ej: 50.00 = 50%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='legacybalanceadjustment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='depreciation_appliance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Electrodomésticos: % depreciación mensual', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='depreciation_console_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.50'), help_text='Consolas: % depreciación mensual', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='depreciation_laptop_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.50'), help_text='Laptops: % depreciación mensual', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='depreciation_other_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Otros: % depreciación mensual', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='depreciation_phone_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.50'), help_text='Celulares: % depreciación mensual', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='gold_price_24k_gram_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('580.00'), help_text='Precio del gramo de oro 24k en Bs (actualizar diariamente)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='hard_block_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('30.00'), help_text='% sobre el máximo recomendado que bloquea y requiere autorización del dueño', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='loan_to_value_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Máximo a prestar como % del valor estimado (ej: 60%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='silver_price_gram_bs',
            field=models.DecimalField(decimal_places=2, default=Decimal('7.50'), help_text='Precio del gramo de plata en Bs', max_digits=10),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='soft_warning_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='% sobre el máximo recomendado que genera advertencia', max_digits=5),
        ),
        migrations.AlterField(
            model_name='mviconfig',
            name='vip_bonus_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='% extra permitido para clientes ORO sobre la recomendación', max_digits=5),
        ),
        migrations.AlterField(
            model_name='pawnamortization',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pawncontract',
            name='interest_mode',
            field=models.CharField(default='FIXED', help_text='FIXED (mensual fijo) / PROMO (condición especial)', max_length=20),
        ),
        migrations.AlterField(
            model_name='pawncontract',
            name='sync_operator_code',
            field=models.CharField(blank=True, default='', help_text='Usuario que digitalizó este contrato.', max_length=20),
        ),
        migrations.AlterField(
            model_name='pawnitem',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excelente'), ('GOOD', 'Bueno'), ('WORN', 'Desgastado'), ('DAMAGED', 'Dañado')], default='GOOD', help_text='Estado del artículo: ajusta la sugerencia MVI', max_length=20),
        ),
        migrations.AlterField(
            model_name='salaryperiod',
            name='afp_deduction_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='0 si no tiene NUA; 12.71 si tiene AFP.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='salaryperiod',
            name='cash_shortage_deduction',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Descuento por faltante de caja justificado.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryperiod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salaryperiod',
            name='performance_bonus',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Bono puntualidad / fidelización, etc.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryperiod',
            name='seniority_bonus_base',
            field=models.DecimalField(decimal_places=2, default=0, help_text='3 × SMN vigente al calcular.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='salaryscale',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='salaryscale',
            name='month_number',
            field=models.PositiveSmallIntegerField(help_text='Mes de trabajo a partir del cual aplica este sueldo (1=primer mes).'),
        ),
        migrations.AlterField(
            model_name='salaryscale',
            name='salary',
            field=models.DecimalField(decimal_places=2, help_text='Sueldo en Bs. para este escalón.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vacationperiod',
            name='accrual_year',
            field=models.PositiveSmallIntegerField(help_text='Año laboral cumplido (1=primer año, 2=segundo año…).'),
        ),
        migrations.AlterField(
            model_name='vacationperiod',
            name='calendar_year',
            field=models.PositiveSmallIntegerField(help_text='Año calendario en que se generó el derecho vacacional.'),
        ),
        migrations.AlterField(
            model_name='vacationperiod',
            name='days_available',
            field=models.PositiveSmallIntegerField(help_text='Días hábiles de vacación disponibles (15, 20 o 30).'),
        ),
        migrations.AlterField(
            model_name='vacationperiod',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
